### ISSUE TITLE
Chybí podpora polí "vytisknout_stitek_prepravce" a "vytvorit_zpetny_stitek".

### ISSUE THREAD

**Issue by WM-Programator-3** [postabezhranic/apisdk#11]
Chybí podpora polí "vytisknout_stitek_prepravce" a "vytvorit_zpetny_stitek".

**Comment by develart-projects** [comment]
Tiež som práve objavil tento problém. Ale keď vidím tie zbytočné private premenné a následne načítanie cez reflection, tak si veru napíšem toto radšej sám :-)
