### ISSUE TITLE
Support for fulfillment

### ISSUE THREAD

**Issue by kopecny-shockworks** [postabezhranic/apisdk#3]
Z dokumentace:
Fulfillment
Odeslání zásilek
Postupuje se stejným způsobem, jako v případě odeslání standardní zásilky, ale do bloku
<zasilka> je přidán element <produkty> s následujícími hodnoty:....

This feature is currently not supported in this library. Can you please add this functionality? Or should I implement it and create pull request?

**Comment by kopecny-shockworks** [comment]
It appears that this commit: https://github.com/postabezhranic/apisdk/commit/3afc7d97291e4e4d3d06f5bc904d58f5b5149be4#diff-6c91dd3036cf229bdae908a6db953d50
introduced the fulfillment funcionality, but then this commit: https://github.com/postabezhranic/apisdk/commit/8dc5e8fc1063388713276e66b2f78e7d046bcf1b#diff-6c91dd3036cf229bdae908a6db953d50
removed that functionality again

**Comment by Matousek** [comment]
Thanks for report. I am release new version [1.4.2](https://github.com/postabezhranic/apisdk/tree/1.4.2) with fulfillment fix.
