### ISSUE TITLE
Kontrola polí obsahuje české názvy; v dokumentaci jsou už anglické

### ISSUE THREAD

**Issue by MichalSkoula** [postabezhranic/apisdk#5]
https://github.com/postabezhranic/apisdk/blob/6c97b9d1f10a5c5bdcac417de34b39e789b9630c/src/Pbh.php#L64

**Comment by MichalSkoula** [comment]
Prosím o opravu :)

**Comment by Matousek** [comment]
opraveno, díky za upozornění

https://github.com/postabezhranic/apisdk/releases/tag/1.6.0
